import { Message, PermissionFlagsBits } from 'discord.js';
import { Command } from '../../lib/structures/Command';
import { EmbedUtils } from '../../utils/EmbedUtils';

export default {
    name: '2fa',
    description: 'Learn how to enable Two-Factor Authentication (Required for Staff).',
    category: 'Info',
    run: async (client, interaction) => {
        const isMessage = interaction instanceof Message;
        const target = isMessage ? interaction.channel : interaction;

        const embed = EmbedUtils.info(
            '🛡️ Two-Factor Authentication (2FA)',
            '**2FA is strictly required** for all Staff and Sub-Team members in the SkyAlert Network. If you do not have 2FA enabled, you cannot hold any official position or utilize staff commands.\n\n### How to Enable 2FA:\n1. Go to your Discord **User Settings** (the gear icon bottom left).\n2. Under the **My Account** tab, find the **Password and Authentication** section.\n3. Click the **Enable Two-Factor Auth** button.\n4. Download an authenticator app on your phone (like **Google Authenticator**, **Microsoft Authenticator**, or **Authy**).\n5. Scan the QR code provided by Discord using the app.\n6. Enter the 6-digit code generated by your app into Discord.\n7. **CRITICAL:** Download your **Backup Codes** and save them somewhere safe!\n\n### 🎥 Video Tutorial\nIf you need a visual guide, watch the official Discord tutorial here:\n👉 **[Discord 2FA Setup Tutorial (YouTube)](https://www.youtube.com/watch?v=J_I5O4-6EFE)**'
        ).setColor('#00ffaa');

        if (isMessage) {
            await target.send({ embeds: [embed] });
        } else {
            await target.reply({ embeds: [embed] });
        }
    }
} as Command;
